# Generated by Django 5.2.7 on 2026-07-30 19:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('stage', models.CharField(choices=[('registration', 'Registration'), ('vitals', 'Vital signs'), ('consultation', 'Consultation'), ('pharmacy', 'Pharmacy'), ('complete', 'Complete')], max_length=32)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive counters keep their history but are not assigned new visits.')),
            ],
            options={
                'ordering': ['stage', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TokenSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'token sequence',
                'verbose_name_plural': 'token sequences',
            },
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('registration_clerk', 'Registration Clerk'), ('nurse_vitals', 'Nurse / Vitals'), ('clinician', 'Clinician'), ('pharmacist', 'Pharmacist'), ('supervisor', 'Supervisor / Management'), ('it_support', 'IT / Support')], help_text='Determines which actions and dashboards this account can reach.', max_length=32)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('default_counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_staff', to='queueapp.servicecounter')),
            ],
            options={
                'verbose_name': 'staff user',
                'verbose_name_plural': 'staff users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(choices=[('registration_clerk', 'Registration Clerk'), ('nurse_vitals', 'Nurse / Vitals'), ('clinician', 'Clinician'), ('pharmacist', 'Pharmacist'), ('supervisor', 'Supervisor / Management'), ('it_support', 'IT / Support')], max_length=32)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('visit_token', models.CharField(blank=True, db_index=True, max_length=16)),
                ('non_sensitive_detail', models.TextField(blank=True, help_text='Never a diagnosis, symptom, prescription or patient identifier.')),
                ('actor_staff_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log entries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=16)),
                ('token_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('check_in_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Recorded at registration. Routine ordering within a stage uses this.')),
                ('current_stage', models.CharField(choices=[('registration', 'Registration'), ('vitals', 'Vital signs'), ('consultation', 'Consultation'), ('pharmacy', 'Pharmacy'), ('complete', 'Complete')], db_index=True, default='registration', max_length=32)),
                ('stage_status', models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In progress'), ('complete', 'Complete')], default='waiting', max_length=16)),
                ('priority', models.CharField(choices=[('emergency', 'Emergency'), ('urgent', 'Urgent'), ('routine', 'Routine')], default='routine', help_text='Set only by authorised clinical roles. Never shown publicly.', max_length=16)),
                ('presence_status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('recalled', 'Recalled'), ('temporarily_away', 'Temporarily away'), ('missed_turn', 'Missed turn'), ('resumed', 'Resumed')], default='waiting', max_length=24)),
                ('notification_preference', models.CharField(choices=[('screen', 'Screen'), ('printed', 'Printed token'), ('sms', 'SMS / phone')], default='screen', max_length=16)),
                ('awaiting_tests', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_counter', models.ForeignKey(blank=True, help_text='The destination shown beside this token on the public display.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='queueapp.servicecounter')),
            ],
            options={
                'ordering': ['check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='StageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('registration', 'Registration'), ('vitals', 'Vital signs'), ('consultation', 'Consultation'), ('pharmacy', 'Pharmacy'), ('complete', 'Complete')], max_length=32)),
                ('entered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by_role', models.CharField(blank=True, choices=[('registration_clerk', 'Registration Clerk'), ('nurse_vitals', 'Nurse / Vitals'), ('clinician', 'Clinician'), ('pharmacist', 'Pharmacist'), ('supervisor', 'Supervisor / Management'), ('it_support', 'IT / Support')], max_length=32)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_events', to='queueapp.visit')),
            ],
            options={
                'ordering': ['entered_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PriorityChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_priority', models.CharField(blank=True, choices=[('emergency', 'Emergency'), ('urgent', 'Urgent'), ('routine', 'Routine')], max_length=16)),
                ('new_priority', models.CharField(choices=[('emergency', 'Emergency'), ('urgent', 'Urgent'), ('routine', 'Routine')], max_length=16)),
                ('changed_by_role', models.CharField(choices=[('registration_clerk', 'Registration Clerk'), ('nurse_vitals', 'Nurse / Vitals'), ('clinician', 'Clinician'), ('pharmacist', 'Pharmacist'), ('supervisor', 'Supervisor / Management'), ('it_support', 'IT / Support')], max_length=32)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('non_sensitive_reason', models.CharField(help_text='Non-sensitive category for the change. Never a diagnosis or symptom.', max_length=120)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_changes', to='queueapp.visit')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('medicine_ready', 'Medicine ready'), ('medicine_issued', 'Medicine issued'), ('medicine_unavailable', 'Medicine unavailable')], max_length=32)),
                ('by_role', models.CharField(choices=[('registration_clerk', 'Registration Clerk'), ('nurse_vitals', 'Nurse / Vitals'), ('clinician', 'Clinician'), ('pharmacist', 'Pharmacist'), ('supervisor', 'Supervisor / Management'), ('it_support', 'IT / Support')], max_length=32)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_outcomes', to='queueapp.visit')),
            ],
            options={
                'ordering': ['timestamp', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_contact', to='queueapp.visit')),
            ],
            options={
                'verbose_name': 'notification contact',
                'verbose_name_plural': 'notification contacts',
            },
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['current_stage', 'stage_status', 'priority', 'check_in_time'], name='visit_queue_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.UniqueConstraint(fields=('token_date', 'token'), name='unique_token_per_day'),
        ),
        migrations.AddIndex(
            model_name='stageevent',
            index=models.Index(fields=['stage', 'completed_at'], name='stage_completed_idx'),
        ),
    ]
