# Generated by Django 5.2.7 on 2026-07-30 20:12

import django.utils.timezone
from django.db import migrations, models
from django.db.models import F


def set_order_time_from_check_in(apps, schema_editor):
    """
    Existing visits keep their place in the queue.

    The new field defaults to "now", which would collapse every waiting
    patient's ordering to the moment of deployment — everyone level-pegged, and
    check-in order lost. Routine fairness is the whole point of FR2, so backfill
    from the time each patient actually arrived.
    """
    apps.get_model("queueapp", "Visit").objects.update(
        queue_order_time=F("check_in_time")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('queueapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='visit',
            name='visit_queue_order_idx',
        ),
        migrations.AddField(
            model_name='visit',
            name='queue_order_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visit',
            name='check_in_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Recorded at registration. Never changes — it is the record.'),
        ),
        migrations.RunPython(
            set_order_time_from_check_in,
            # Reversing drops the column, so there is nothing to undo.
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['current_stage', 'stage_status', 'priority', 'queue_order_time'], name='visit_queue_order_idx'),
        ),
    ]
